-- Repara el encoding corrupto del import inicial (acentos convertidos en ??).
-- Fuente: data/escuelas.json de la PWA (UTF-8 correcto). Solo toca ids conocidos.

UPDATE schools SET name='Agüero', location='Agüero', region='Aragón', style='Vía', rock_type='Conglomerado' WHERE id='aguero';
UPDATE schools SET name='Albarracín', location='Provincia de Teruel, Albarracín', region='Aragón', style='Bloque', rock_type='Arenisca' WHERE id='albarracin';
UPDATE schools SET name='Alcañiz', location='Provincia de Teruel, Alcañiz', region='Aragón', style='Bloque', rock_type='Arenisca' WHERE id='alcaniz';
UPDATE schools SET name='Alfondeguilla', location='Alfondeguilla', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='alfondeguilla';
UPDATE schools SET name='Alhama de Granada', location='Alhama de Granada', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='alhama-de-granada';
UPDATE schools SET name='Almorchón, El (Cieza)', location='Cieza', region='Región de Murcia', style='Vía', rock_type='Caliza' WHERE id='almorchon-el-cieza';
UPDATE schools SET name='Alos de Balaguer (Alos de Balaguer)', location='Alòs de Balaguer', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='alos-de-balaguer-alos-de-balaguer';
UPDATE schools SET name='Alquézar (Alquézar)', location='Alquézar', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='alquezar-alquezar';
UPDATE schools SET name='Ansó', location='Ansó', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='anso';
UPDATE schools SET name='Araotz', location='Oñati', region='País Vasco', style='Vía', rock_type='Caliza' WHERE id='araotz';
UPDATE schools SET name='Archidona', location='Archidona', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='archidona';
UPDATE schools SET name='Arenas de San Pedro', location='Arenas de San Pedro', region='Castilla y León', style='Vía', rock_type='Granito' WHERE id='arenas-de-san-pedro';
UPDATE schools SET name='Arico Nuevo', location='Tenerife, Arico', region='Canarias', style='Bloque', rock_type='Basalto' WHERE id='arico-nuevo';
UPDATE schools SET name='Atxarte', location='Atxarte', region='País Vasco', style='Vía', rock_type='Caliza' WHERE id='atxarte';
UPDATE schools SET name='Baltzola', location='Galdakao', region='País Vasco', style='Bloque', rock_type='Caliza' WHERE id='baltzola';
UPDATE schools SET name='Barranco El Fuerte (Illar)', location='Íllar', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='barranco-el-fuerte-illar';
UPDATE schools SET name='Barranco la Madera (Santa Cruz de la Palma)', location='Santa Cruz de La Palma', region='Canarias', style='Vía', rock_type='Volcánica' WHERE id='barranco-la-madera-santa-cruz-de-la-palma';
UPDATE schools SET name='Becedas', location='Provincia de Ávila, Becedas', region='Castilla y León', style='Bloque', rock_type='Granito' WHERE id='becedas';
UPDATE schools SET name='Beceite', location='Beceite', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='beceite';
UPDATE schools SET name='Berga (Berga)', location='Berga', region='Cataluña', style='Vía', rock_type='Conglomerado' WHERE id='berga-berga';
UPDATE schools SET name='Beuda (Beuda)', location='Beuda', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='beuda-beuda';
UPDATE schools SET name='Bielsa', location='Bielsa', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='bielsa';
UPDATE schools SET name='Buey, El (Jumilla)', location='Jumilla', region='Región de Murcia', style='Vía', rock_type='Caliza' WHERE id='buey-el-jumilla';
UPDATE schools SET name='Bujeo, El (Tarifa)', location='Tarifa', region='Andalucía', style='Bloque', rock_type='Arenisca' WHERE id='bujeo-el-tarifa';
UPDATE schools SET name='Bustarviejo', location='Bustarviejo', region='Comunidad de Madrid', style='Bloque', rock_type='Granito' WHERE id='bustarviejo';
UPDATE schools SET name='Buñol', location='Buñol', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='bunol';
UPDATE schools SET name='Cabañas del Castillo (Cabañas del Castillo)', location='Cabañas del Castillo', region='Extremadura', style='Vía', rock_type='Cuarcita' WHERE id='cabanas-del-castillo-cabanas-del-castillo';
UPDATE schools SET name='Cadira del Bisbe, La (Premiá de Dalt)', location='Premià de Dalt', region='Cataluña', style='Vía', rock_type='Granito' WHERE id='cadira-del-bisbe-la-premia-de-dalt';
UPDATE schools SET name='Calcena (Calcena)', location='Calcena', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='calcena-calcena';
UPDATE schools SET name='Cales Coves (Sant Climent, Menorca)', location='Sant Climent, Menorca', region='Islas Baleares', style='Vía', rock_type='Caliza' WHERE id='cales-coves-sant-climent-menorca';
UPDATE schools SET name='Calpe', location='Calpe', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='calpe';
UPDATE schools SET name='Camarasa', location='Camarasa', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='camarasa';
UPDATE schools SET name='Can Boquet', location='Vilassar de Dalt / colinas de Barcelona', region='Cataluña', style='Bloque', rock_type='Granito' WHERE id='can-boquet';
UPDATE schools SET name='Castell de Santueri (Celanita)', location='Felanitx / Castell de Santueri', region='Islas Baleares', style='Vía', rock_type='Caliza' WHERE id='castell-de-santueri-celanita';
UPDATE schools SET name='Castellet (Castellón de la Plana)', location='Castellón de la Plana', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='castellet-castellon-de-la-plana';
UPDATE schools SET name='Castillo de Bayuela', location='Provincia de Toledo, Castillo de Bayuela', region='Castilla-La Mancha', style='Vía', rock_type='Granito' WHERE id='castillo-de-bayuela';
UPDATE schools SET name='Castro de Baroña (Baroña, Porto do son)', location='Baroña, Porto do Son', region='Galicia', style='Vía', rock_type='Granito' WHERE id='castro-de-barona-barona-porto-do-son';
UPDATE schools SET name='Cazorla', location='Cazorla', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='cazorla';
UPDATE schools SET name='Cañón de Manilva (Manilva)', location='Manilva', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='canon-de-manilva-manilva';
UPDATE schools SET name='Chulilla', location='Chulilla (Valencia)', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='chulilla';
UPDATE schools SET name='Circo de Gredos (Hoyos del Espino)', location='Hoyos del Espino', region='Castilla y León', style='Vía', rock_type='Granito' WHERE id='circo-de-gredos-hoyos-del-espino';
UPDATE schools SET name='Ciudad Encantada de Tamajón', location='Guadalajara, Tamajón', region='Castilla-La Mancha', style='Bloque', rock_type='Caliza' WHERE id='ciudad-encantada-de-tamajon';
UPDATE schools SET name='Coallafu (Coallafu)', location='Coalla / Grado', region='Asturias', style='Vía', rock_type='Caliza' WHERE id='coallafu-coallafu';
UPDATE schools SET name='Collegats', location='La Pobla de Segur', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='collegats';
UPDATE schools SET name='Colmenar Viejo', location='Colmenar Viejo', region='Comunidad de Madrid', style='Vía', rock_type='Granito' WHERE id='colmenar-viejo';
UPDATE schools SET name='Congosto de Alcorlo (San Andrés de Congosto)', location='San Andrés de Congosto', region='Castilla-La Mancha', style='Vía', rock_type='Caliza' WHERE id='congosto-de-alcorlo-san-andres-de-congosto';
UPDATE schools SET name='Corme', location='O Porto de Corme, Ponteceso (A Coruña)', region='Galicia', style='Bloque', rock_type='Granito' WHERE id='corme';
UPDATE schools SET name='Corona, La y La Trona (Centelles)', location='Centelles', region='Cataluña', style='Vía', rock_type='Arenisca' WHERE id='corona-la-y-la-trona-centelles';
UPDATE schools SET name='Crevillent', location='Crevillent', region='Comunidad Valenciana', style='Bloque', rock_type=NULL WHERE id='crevillent';
UPDATE schools SET name='Cuenca', location='Cuenca, Ciudad de Cuenca', region='Castilla-La Mancha', style='Vía', rock_type='Caliza' WHERE id='cuenca';
UPDATE schools SET name='Dos Hermanas-Biaizpe (Irurtzun)', location='Irurtzun', region='Navarra', style='Vía', rock_type='Caliza' WHERE id='dos-hermanas-biaizpe-irurtzun';
UPDATE schools SET name='Eguino', location='Arrasate', region='País Vasco', style='Bloque', rock_type='Caliza' WHERE id='eguino';
UPDATE schools SET name='El Bancal', location='Crevillent, Alicante', region='Comunidad Valenciana', style='Bloque', rock_type='Caliza' WHERE id='el-bancal';
UPDATE schools SET name='El Barraco', location='El Barraco', region='Castilla y León', style='Vía', rock_type='Granito' WHERE id='el-barraco';
UPDATE schools SET name='El Burguillo', location='Provincia de Ávila, El Tiemblo', region='Castilla y León', style='Bloque', rock_type='Granito' WHERE id='el-burguillo';
UPDATE schools SET name='El Chorro', location='Ardales', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='el-chorro';
UPDATE schools SET name='El Cogul', location='El Cogul (Lleida)', region='Cataluña', style='Bloque', rock_type='Arenisca' WHERE id='el-cogul';
UPDATE schools SET name='El Escorial', location='Madrid, El Escorial', region='Comunidad de Madrid', style='Bloque', rock_type='Granito' WHERE id='el-escorial';
UPDATE schools SET name='El Torcal de Antequera', location='Antequera', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='el-torcal-de-antequera';
UPDATE schools SET name='Es Verger (Esporles)', location='Esporles', region='Islas Baleares', style='Vía', rock_type='Caliza' WHERE id='es-verger-esporles';
UPDATE schools SET name='Escales (Pont de Suert)', location='El Pont de Suert', region='Cataluña', style='Vía', rock_type='Granito' WHERE id='escales-pont-de-suert';
UPDATE schools SET name='Etxauri', location='Etxauri', region='Navarra', style='Vía', rock_type='Caliza' WHERE id='etxauri';
UPDATE schools SET name='Etxauri Bloque', location='Etxauri', region='Navarra', style='Bloque', rock_type='Caliza' WHERE id='etxauri-bloque';
UPDATE schools SET name='Foradá (Petrer)', location='Petrer', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='forada-petrer';
UPDATE schools SET name='Formentor', location='Formentor', region='Islas Baleares', style='Vía', rock_type='Caliza' WHERE id='formentor';
UPDATE schools SET name='Fragas del Sil (Ponferrada)', location='Ponferrada', region='Castilla y León', style='Vía', rock_type='Pizarra' WHERE id='fragas-del-sil-ponferrada';
UPDATE schools SET name='Fraguels (Bunyola)', location='Bunyola', region='Islas Baleares', style='Vía', rock_type='Caliza' WHERE id='fraguels-bunyola';
UPDATE schools SET name='Frigiliana', location='Frigiliana', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='frigiliana';
UPDATE schools SET name='Fuixarda, La (Barcelona)', location='Barcelona', region='Cataluña', style='Vía', rock_type='Arenisca' WHERE id='fuixarda-la-barcelona';
UPDATE schools SET name='Gandía', location='Gandía', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='gandia';
UPDATE schools SET name='Guadalest', location='Guadalest', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='guadalest';
UPDATE schools SET name='Hoces de Vegacervera (Vegacervera)', location='Vegacervera', region='Castilla y León', style='Vía', rock_type='Caliza' WHERE id='hoces-de-vegacervera-vegacervera';
UPDATE schools SET name='Hoces del Duratón', location='Sepúlveda', region='Castilla y León', style='Vía', rock_type='Caliza' WHERE id='hoces-del-duraton';
UPDATE schools SET name='Hoyamoros', location='Provincia de Salamanca, Candelario', region='Castilla y León', style='Bloque', rock_type='Granito' WHERE id='hoyamoros';
UPDATE schools SET name='Hoz de la Vieja', location='Hoz de la Vieja', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='hoz-de-la-vieja';
UPDATE schools SET name='Huesa del Coman (Huesa del Coman)', location='Huesa del Común', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='huesa-del-coman-huesa-del-coman';
UPDATE schools SET name='Jaizkibel', location='Gipuzkoa, Jaizkibel', region='País Vasco', style='Bloque', rock_type='Arenisca' WHERE id='jaizkibel';
UPDATE schools SET name='Jameo de la Puerta Falsa (Haría. Lanzarote)', location='Haría, Lanzarote', region='Canarias', style='Vía', rock_type='Volcánica' WHERE id='jameo-de-la-puerta-falsa-haria-lanzarote';
UPDATE schools SET name='Jaraba (Jaraba)', location='Jaraba', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='jaraba-jaraba';
UPDATE schools SET name='Kantera (Azpeitia)', location='Azpeitia', region='País Vasco', style='Vía', rock_type='Caliza' WHERE id='kantera-azpeitia';
UPDATE schools SET name='La Boyeriza (Geras de Gordón)', location='Geras de Gordón', region='Castilla y León', style='Vía', rock_type='Caliza' WHERE id='la-boyeriza-geras-de-gordon';
UPDATE schools SET name='La Cabrera', location='La Cabrera', region='Comunidad de Madrid', style='Vía', rock_type='Granito' WHERE id='la-cabrera';
UPDATE schools SET name='La Comarca', location='Provincia de Barcelona, Les Masies de Roda', region='Cataluña', style='Bloque', rock_type='Arenisca' WHERE id='la-comarca';
UPDATE schools SET name='La Jonquera (Puig del Corb)', location='Girona, La Jonquera / Cantallops', region='Cataluña', style='Bloque', rock_type='Granito' WHERE id='la-jonquera-puig-del-corb';
UPDATE schools SET name='La Panocha', location='Murcia', region='Región de Murcia', style='Vía', rock_type='Caliza' WHERE id='la-panocha';
UPDATE schools SET name='La Pedriza', location='Madrid, Manzanares el Real', region='Comunidad de Madrid', style='Vía', rock_type='Granito' WHERE id='la-pedriza';
UPDATE schools SET name='La Ñora', location='Gijón, San Clemente', region='Asturias', style='Bloque', rock_type='Conglomerado' WHERE id='la-nora';
UPDATE schools SET name='Laguna Negra (Vinuesa)', location='Vinuesa', region='Castilla y León', style='Vía', rock_type='Granito' WHERE id='laguna-negra-vinuesa';
UPDATE schools SET name='Larraona', location='Larraona (Navarra)', region='Navarra', style='Bloque', rock_type='Caliza' WHERE id='larraona';
UPDATE schools SET name='Larraona Bloque', location='Larraona', region='Navarra', style='Bloque', rock_type='Caliza' WHERE id='larraona-bloque';
UPDATE schools SET name='Las Tuerces', location='Palencia, Villaescusa de las Torres / Las Tuerces', region='Castilla y León', style='Bloque', rock_type='Caliza' WHERE id='las-tuerces';
UPDATE schools SET name='Leiva', location='Alhama de Murcia', region='Región de Murcia', style='Vía', rock_type='Caliza' WHERE id='leiva';
UPDATE schools SET name='Ligüerre de Cinca (Ainsa)', location='Aínsa', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='liguerre-de-cinca-ainsa';
UPDATE schools SET name='Loja', location='Loja', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='loja';
UPDATE schools SET name='Los Barruecos', location='Cáceres', region='Extremadura', style='Bloque', rock_type='Granito' WHERE id='los-barruecos';
UPDATE schools SET name='Los Cahorros', location='Monachil', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='los-cahorros';
UPDATE schools SET name='Lumbier', location='Lumbier', region='Navarra', style='Vía', rock_type='Caliza' WHERE id='lumbier';
UPDATE schools SET name='Mallos de Riglos', location='Las Peñas de Riglos', region='Aragón', style='Vía', rock_type='Conglomerado' WHERE id='mallos-de-riglos';
UPDATE schools SET name='Mallos de Vadiello', location='Balneario de Panticosa', region='Aragón', style='Vía', rock_type='Conglomerado' WHERE id='mallos-de-vadiello';
UPDATE schools SET name='Margalef', location='Margalef de Montsant (Tarragona)', region='Cataluña', style='Vía', rock_type='Conglomerado' WHERE id='margalef';
UPDATE schools SET name='Mijas (Mijas)', location='Mijas', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='mijas-mijas';
UPDATE schools SET name='Moclín', location='Moclín', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='moclin';
UPDATE schools SET name='Mogán', location='Mogán', region='Canarias', style='Bloque', rock_type=NULL WHERE id='mogan';
UPDATE schools SET name='Monfragüe', location='Plasencia', region='Extremadura', style='Vía', rock_type='Cuarcita' WHERE id='monfrague';
UPDATE schools SET name='Mont-Ral (Mont-Ral)', location='Mont-ral', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='mont-ral-mont-ral';
UPDATE schools SET name='Montanejos', location='Montanejos', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='montanejos';
UPDATE schools SET name='Monte Galiñeiro (Vincios)', location='Vincios', region='Galicia', style='Vía', rock_type='Granito' WHERE id='monte-galineiro-vincios';
UPDATE schools SET name='Montsant', location='Ulldemolins', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='montsant';
UPDATE schools SET name='Montserrat', location='Montserrat', region='Cataluña', style='Vía', rock_type='Conglomerado' WHERE id='montserrat';
UPDATE schools SET name='Morata de Jalón', location='Morata de Jalón', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='morata-de-jalon';
UPDATE schools SET name='Muelas, Las (Muelas del Pan)', location='Muelas del Pan', region='Castilla y León', style='Vía', rock_type='Granito' WHERE id='muelas-las-muelas-del-pan';
UPDATE schools SET name='Naranjo de Bulnes', location='Arenas de Cabrales', region='Asturias', style='Vía', rock_type='Caliza' WHERE id='naranjo-de-bulnes';
UPDATE schools SET name='Navalosa', location='Provincia de Ávila, Navalosa', region='Castilla y León', style='Bloque', rock_type='Granito' WHERE id='navalosa';
UPDATE schools SET name='Nuévalos', location='Nuévalos', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='nuevalos';
UPDATE schools SET name='Ogoño', location='Ibarrangelu', region='País Vasco', style='Vía', rock_type='Caliza' WHERE id='ogono';
UPDATE schools SET name='Oliana (Contrafot de Rumbau)', location='Oliana', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='oliana-contrafot-de-rumbau';
UPDATE schools SET name='Onís', location='Onís', region='Asturias', style='Vía', rock_type='Caliza' WHERE id='onis';
UPDATE schools SET name='Ordesa (Torla)', location='Torla / Ordesa', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='ordesa-torla';
UPDATE schools SET name='Pancorbo', location='Pancorbo', region='Castilla y León', style='Vía', rock_type='Caliza' WHERE id='pancorbo';
UPDATE schools SET name='Panticosa (Panticosa)', location='Panticosa', region='Aragón', style='Vía', rock_type='Granito' WHERE id='panticosa-panticosa';
UPDATE schools SET name='Pared de Catalunya-Montrebei (Pont de Montanyana)', location='Pont de Montanyana / Montrebei', region='Aragón / Cataluña', style='Vía', rock_type='Caliza' WHERE id='pared-de-catalunya-montrebei-pont-de-montanyana';
UPDATE schools SET name='Pared Negra. Frontal de Orihuela (Orihuela)', location='Orihuela', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='pared-negra-frontal-de-orihuela-orihuela';
UPDATE schools SET name='Patones Pueblo', location='Patones / Sierra Norte de Madrid', region='Comunidad de Madrid', style='Vía', rock_type='Caliza / calcoarenita' WHERE id='patones-pueblo';
UPDATE schools SET name='Pedraforca (Saldes)', location='Saldes', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='pedraforca-saldes';
UPDATE schools SET name='Pena Corneira', location='Provincia de Ourense, Leiro', region='Galicia', style='Bloque', rock_type='Granito' WHERE id='pena-corneira';
UPDATE schools SET name='Pena do Encanto', location='Leiro', region='Galicia', style='Vía', rock_type='Granito' WHERE id='pena-do-encanto';
UPDATE schools SET name='Petón do Xalo (Castelo)', location='Castelo', region='Galicia', style='Vía', rock_type='Granito' WHERE id='peton-do-xalo-castelo';
UPDATE schools SET name='Peña Amaya', location='Merindad de Castilla Vieja', region='Castilla y León', style='Vía', rock_type='Caliza' WHERE id='pena-amaya';
UPDATE schools SET name='Peñarrubia', location='Guadalix de la Sierra (Madrid)', region='Comunidad de Madrid', style='Vía', rock_type='Caliza' WHERE id='penarrubia';
UPDATE schools SET name='Pic de l’Aliga (Sant Andreu de la Barca)', location='Sant Andreu de la Barca', region='Cataluña', style='Vía', rock_type='Conglomerado' WHERE id='pic-de-l-aliga-sant-andreu-de-la-barca';
UPDATE schools SET name='Pico Sacro', location='Boqueixón', region='Galicia', style='Vía', rock_type='Cuarcita' WHERE id='pico-sacro';
UPDATE schools SET name='Picos de Europa', location='Picos de Europa', region='Asturias / Cantabria / Leon', style='Vía', rock_type='Caliza' WHERE id='picos-de-europa';
UPDATE schools SET name='Pitarejo (Pitarque)', location='Pitarque', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='pitarejo-pitarque';
UPDATE schools SET name='Pontons (Pontons)', location='Pontons', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='pontons-pontons';
UPDATE schools SET name='Pontón de la Oliva', location='Buitrago de Lozoya', region='Comunidad de Madrid', style='Vía', rock_type='Caliza' WHERE id='ponton-de-la-oliva';
UPDATE schools SET name='Poyatos (Algatocín)', location='Algatocín', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='poyatos-algatocin';
UPDATE schools SET name='Presa do Eume (Goente)', location='Goente', region='Galicia', style='Vía', rock_type='Granito' WHERE id='presa-do-eume-goente';
UPDATE schools SET name='Proaza', location='Proaza', region='Asturias', style='Vía', rock_type='Caliza' WHERE id='proaza';
UPDATE schools SET name='Puerto Roque (Valencia de Alcántara)', location='Valencia de Alcántara', region='Extremadura', style='Vía', rock_type='Cuarcita' WHERE id='puerto-roque-valencia-de-alcantara';
UPDATE schools SET name='Punta Nariga', location='A Coruña, Mens', region='Galicia', style='Bloque', rock_type='Granito' WHERE id='punta-nariga';
UPDATE schools SET name='Quirós (Aciera)', location='Aciera / Quirós', region='Asturias', style='Vía', rock_type='Caliza' WHERE id='quiros-aciera';
UPDATE schools SET name='Ramales de la Victoria', location='Ramales de la Victoria', region='Cantabria', style='Vía', rock_type='Caliza' WHERE id='ramales-de-la-victoria';
UPDATE schools SET name='Recuchillo (jaén)', location='Jaén', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='recuchillo-jaen';
UPDATE schools SET name='Reguchillo', location='Cordel de Jabalcuz, Jaén', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='reguchillo';
UPDATE schools SET name='Remuñe (Benasque)', location='Benasque', region='Aragón', style='Vía', rock_type='Granito' WHERE id='remune-benasque';
UPDATE schools SET name='Resconorio', location='Cantabria, Entrambasmestas / Bustiyerro', region='Comunidad Autónoma de Cantabria', style='Bloque', rock_type='Arenisca' WHERE id='resconorio';
UPDATE schools SET name='Rincón de Bonanza (Orihuela)', location='Orihuela', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='rincon-de-bonanza-orihuela';
UPDATE schools SET name='Rodellar', location='Rodellar, Bierge (Huesca)', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='rodellar';
UPDATE schools SET name='Ronda', location='Ronda', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='ronda';
UPDATE schools SET name='Roque Nublo (Ayacata. Gran Canaria)', location='Ayacata, Gran Canaria', region='Canarias', style='Vía', rock_type='Volcánica' WHERE id='roque-nublo-ayacata-gran-canaria';
UPDATE schools SET name='Rozas', location='Pedrosa de Valdeporres, Burgos', region='Castilla y León', style='Bloque', rock_type='Arenisca' WHERE id='rozas';
UPDATE schools SET name='Sa Gubia', location='Bunyola', region='Islas Baleares', style='Vía', rock_type='Caliza' WHERE id='sa-gubia';
UPDATE schools SET name='Salto del Gallo (Almería)', location='Almería', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='salto-del-gallo-almeria';
UPDATE schools SET name='San Martín de Ubierna (San Martín de Ubierna)', location='San Martín de Ubierna', region='Castilla y León', style='Vía', rock_type='Caliza' WHERE id='san-martin-de-ubierna-san-martin-de-ubierna';
UPDATE schools SET name='Sant Llorenç del Munt', location='Sant Llorenç del Munt', region='Cataluña', style='Vía', rock_type='Conglomerado' WHERE id='sant-llorenc-del-munt';
UPDATE schools SET name='Santa Gadea', location='Burgos, Santa Gadea de Alfoz', region='Castilla y León', style='Bloque', rock_type='Arenisca' WHERE id='santa-gadea';
UPDATE schools SET name='Santa Linya', location='Santa Linya, Balaguer (Lleida)', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='santa-linya';
UPDATE schools SET name='Savassona', location='Tavèrnoles', region='Cataluña', style='Bloque', rock_type='Arenisca' WHERE id='savassona';
UPDATE schools SET name='Sedano', location='Sedano', region='Castilla y León', style='Vía', rock_type='Caliza' WHERE id='sedano';
UPDATE schools SET name='Segad (Caldas de Reis)', location='Caldas de Reis', region='Galicia', style='Vía', rock_type='Granito' WHERE id='segad-caldas-de-reis';
UPDATE schools SET name='Sella', location='Sella', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='sella';
UPDATE schools SET name='Siurana (Siurana de Prades)', location='Siurana de Prades', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='siurana-siurana-de-prades';
UPDATE schools SET name='Tales (Onda)', location='Onda / Tales', region='Comunidad Valenciana', style='Vía', rock_type='Arenisca' WHERE id='tales-onda';
UPDATE schools SET name='Tamadaba', location='Gran Canaria', region='Canarias', style='Vía', rock_type='Volcánica' WHERE id='tamadaba';
UPDATE schools SET name='Tavertet', location='Tavertet', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='tavertet';
UPDATE schools SET name='Terradets', location='Cellers', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='terradets';
UPDATE schools SET name='Teverga', location='Asturias, Entrago / Teverga', region='Asturias', style='Vía', rock_type='Caliza' WHERE id='teverga';
UPDATE schools SET name='Torrelaguna', location='Torrelaguna', region='Comunidad de Madrid', style='Vía', rock_type='Caliza' WHERE id='torrelaguna';
UPDATE schools SET name='Torrelodones', location='Torrelodones', region='Comunidad de Madrid', style='Bloque', rock_type='Granito' WHERE id='torrelodones';
UPDATE schools SET name='Tres Ponts', location='Coll de Nargó', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='tres-ponts';
UPDATE schools SET name='Ubrique', location='Ubrique', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='ubrique';
UPDATE schools SET name='Urbasa', location='Urbasa', region='Navarra', style='Vía', rock_type='Caliza' WHERE id='urbasa';
UPDATE schools SET name='Uxola (Alcoy)', location='Alcoy', region='Comunidad Valenciana', style='Vía', rock_type='Caliza' WHERE id='uxola-alcoy';
UPDATE schools SET name='Valcorchero', location='Monte Valcorchero, Plasencia', region='Extremadura', style='Bloque', rock_type='Granito' WHERE id='valcorchero';
UPDATE schools SET name='Valdemanco', location='Valdemanco', region='Comunidad de Madrid', style='Vía', rock_type='Granito' WHERE id='valdemanco';
UPDATE schools SET name='Valdesangil', location='Valdesangil', region='Castilla y León', style='Bloque', rock_type=NULL WHERE id='valdesangil';
UPDATE schools SET name='Valle de Hecho', location='Hecho', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='valle-de-hecho';
UPDATE schools SET name='Valle de Isábena (Beranuy y Merli)', location='Beranuy y Merli', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='valle-de-isabena-beranuy-y-merli';
UPDATE schools SET name='Valle de Valdeón (Caín)', location='Posada de Valdeón', region='Castilla y León', style='Bloque', rock_type='Caliza' WHERE id='valle-de-valdeon-cain';
UPDATE schools SET name='Valle del Jerte', location='Jerte', region='Extremadura', style='Vía', rock_type='Granito' WHERE id='valle-del-jerte';
UPDATE schools SET name='Valsaín', location='La Granja de San Ildefonso', region='Castilla y León', style='Bloque', rock_type='Granito' WHERE id='valsain';
UPDATE schools SET name='Velez de Benaudalla (Velez)', location='Vélez de Benaudalla', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='velez-de-benaudalla-velez';
UPDATE schools SET name='Venteadero o Ventorro de Pelayo (Béjar)', location='Béjar', region='Castilla y León', style='Vía', rock_type='Otra / muro barrenado' WHERE id='venteadero-o-ventorro-de-pelayo-bejar';
UPDATE schools SET name='Vilafamés', location='Vilafamés (Castellón)', region='Comunidad Valenciana', style='Bloque', rock_type='Arenisca' WHERE id='vilafames';
UPDATE schools SET name='Vilanova de Meià', location='Vilanova de Meià', region='Cataluña', style='Vía', rock_type='Caliza' WHERE id='vilanova-de-meia';
UPDATE schools SET name='Villanueva del Rosario', location='Villanueva del Rosario', region='Andalucía', style='Vía', rock_type='Caliza' WHERE id='villanueva-del-rosario';
UPDATE schools SET name='Villanúa', location='Villanúa', region='Aragón', style='Vía', rock_type='Caliza' WHERE id='villanua';
UPDATE schools SET name='Zarzalejo', location='Pajares / Zarzalejo (Madrid)', region='Comunidad de Madrid', style='Bloque', rock_type='Granito' WHERE id='zarzalejo';
UPDATE schools SET name='Ódena', location='Igualada', region='Cataluña', style='Bloque', rock_type='Arenisca' WHERE id='odena';
UPDATE schools SET name='Dehesa de Candelario', location='Candelario', region='Castilla y León', style='Bloque', rock_type='Granito' WHERE id='dehesa-de-candelario';
UPDATE schools SET name='Recuevas', location='Recuevas', region='Castilla y León', style='Vía', rock_type='Caliza' WHERE id='recuevas';
